dist: bionic
language: node_js
node_js:
  - 12
services:
  - docker
jobs:
  include:
    - stage: build and test
      script:
        - ./test.sh        
    - stage: docker push
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - ./clean.sh        
        - docker build -t philipskinner/elemental:latest -f docker/core.dockerfile src/
        - docker push philipskinner/elemental:latest    