services:
  core_services:
    build:
      context: ./docker
      dockerfile: ./core_services.dockerfile
    depends_on:
      - mysql      
      - mailhog
    networks:
      - all  

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - all

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - all

networks:
  all: